### ISSUE TITLE
crash with quark and novam terram 

### ISSUE THREAD

**Issue by spyguy26** [Azmalent/backported-flora#1] opened 2020-09-26 11:49 UTC
Mod Versions:
backportedflora-1.5
Novam+Terram+1.12.2+-+7.3
Forgelin-1.8.4
Quark-r1.6-179
AutoRegLib-1.3-32
Forge-14.23.5.2847

Crash description:
when exploring a world with said mods installed the game crashes during world gen
to reproduce use seed 4586514347051193556 and teleport to x=-799.61, y=80.86, z=399.10

Crash Log:
https://gist.github.com/spyguy26/0f2ed45c8bc44eec0e5e227f16546b7f

**Comment by mmmilord** [comment] 2020-09-27 14:38
Got the same error

Nothing to do with Novam Terram though, don't have that mod.

https://gist.github.com/mmmilord/5b6139957473a555aa5eb69065e422a7

**Comment by Landiie** [comment] 2020-10-06 06:56
same error and crashlog, however i had vanillafix installed and it told me the mods being suspect were backported flora, and quark. i dont have novam terram, so i agree with @mmmilord in that its not related to novam terram. [here's my crash report](https://pastebin.com/Fk5wXxUG).

**Comment by Azmalent** [comment] 2020-10-10 18:58
Judging by the logs it's caused by Quark simulating the use of bonemeal to generate its lush caves. 
Shouldn't be too difficult to fix, I'll look into it

**Comment by Azmalent** [comment] 2020-10-11 02:27
Seems to be fixed now.

**Closed as completed by Azmalent** 2020-10-11 02:27 UTC
